### ISSUE TITLE
Tilde key

### ISSUE THREAD

**Issue by DerfJagged** [zdimension/usbrawmap#5]
Is there a way to map to the tilde / backtick key? I didn't see one in vk.rs. By default, mine is mapped to Escape.

**Comment by zdimension** [comment]
Huh, good question. According to this list maybe VK_OEM_3?

http://www.kbdedit.com/manual/low_level_vk_list.html

I don't have a QWERTY keyboard on hand to test unfortunately

**Comment by DerfJagged** [comment]
That did the trick, thanks!

**Comment by zdimension** [comment]
Nice! I'll add that list to the README
